package isolang

// IsoLang represents an ISO 639-1 language code as a string type.
type IsoLang string

// List of ISO 639-1 language codes.
const (
	Afrikaans   IsoLang = "af"
	Albanian    IsoLang = "sq"
	Amharic     IsoLang = "am"
	Arabic      IsoLang = "ar"
	Armenian    IsoLang = "hy"
	Azerbaijani IsoLang = "az"
	Basque      IsoLang = "eu"
	Belarusian  IsoLang = "be"
	Bengali     IsoLang = "bn"
	Bosnian     IsoLang = "bs"
	Bulgarian   IsoLang = "bg"
	Catalan     IsoLang = "ca"
	Chinese     IsoLang = "zh"
	Croatian    IsoLang = "hr"
	Czech       IsoLang = "cs"
	Danish      IsoLang = "da"
	Dutch       IsoLang = "nl"
	English     IsoLang = "en"
	Esperanto   IsoLang = "eo"
	Estonian    IsoLang = "et"
	Finnish     IsoLang = "fi"
	French      IsoLang = "fr"
	Georgian    IsoLang = "ka"
	German      IsoLang = "de"
	Greek       IsoLang = "el"
	Gujarati    IsoLang = "gu"
	Hebrew      IsoLang = "he"
	Hindi       IsoLang = "hi"
	Hungarian   IsoLang = "hu"
	Icelandic   IsoLang = "is"
	Indonesian  IsoLang = "id"
	Irish       IsoLang = "ga"
	Italian     IsoLang = "it"
	Japanese    IsoLang = "ja"
	Kannada     IsoLang = "kn"
	Kazakh      IsoLang = "kk"
	Korean      IsoLang = "ko"
	Kurdish     IsoLang = "ku"
	Lao         IsoLang = "lo"
	Latvian     IsoLang = "lv"
	Lithuanian  IsoLang = "lt"
	Macedonian  IsoLang = "mk"
	Malay       IsoLang = "ms"
	Malayalam   IsoLang = "ml"
	Maltese     IsoLang = "mt"
	Marathi     IsoLang = "mr"
	Mongolian   IsoLang = "mn"
	Nepali      IsoLang = "ne"
	Norwegian   IsoLang = "no"
	Pashto      IsoLang = "ps"
	Persian     IsoLang = "fa"
	Polish      IsoLang = "pl"
	Portuguese  IsoLang = "pt"
	Punjabi     IsoLang = "pa"
	Romanian    IsoLang = "ro"
	Russian     IsoLang = "ru"
	Serbian     IsoLang = "sr"
	Sinhala     IsoLang = "si"
	Slovak      IsoLang = "sk"
	Slovenian   IsoLang = "sl"
	Somali      IsoLang = "so"
	Spanish     IsoLang = "es"
	Swahili     IsoLang = "sw"
	Swedish     IsoLang = "sv"
	Tamil       IsoLang = "ta"
	Telugu      IsoLang = "te"
	Thai        IsoLang = "th"
	Turkish     IsoLang = "tr"
	Ukrainian   IsoLang = "uk"
	Urdu        IsoLang = "ur"
	Uzbek       IsoLang = "uz"
	Vietnamese  IsoLang = "vi"
	Welsh       IsoLang = "cy"
	Xhosa       IsoLang = "xh"
	Yoruba      IsoLang = "yo"
	Zulu        IsoLang = "zu"
)
